### PR TITLE
Added a way to iterate over channels until they are closed

### PR DESCRIPTION
**Pull request by andreaferretti**
I am no sure how to run tests, but I can add them if you tell me

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
You run the tests with "make check". Take a look at the existing tests in the tests/ directory and at how they are listed in Makefile.am. Do you have some test cases for this iterator? Some behavior you want to mimic? Let's put them in the test suite.

**Comment by andreaferretti** [comment]
I would like to emulate `range` in go, that is, iterating over the values produced by the channel until it is closed. Not that I am an expert in go. My first attempt at your library was translating this example

``` go
package main

import "fmt"

func numberGen(start, count int, out chan<- int) {
    for i := 0; i < count; i++ {
        out <- start + i
    }
    close(out)
}

func printNumbers(in <-chan int, done chan<- bool) {
    for num := range in {
        fmt.Printf("%d\n", num)
    }
    done <- true
}

func main() {
    numberChan := make(chan int)
    done := make(chan bool)
    go numberGen(1, 10, numberChan)
    go printNumbers(numberChan, done)

    <-done
}
```

into this

``` nim
import golib

iterator items*[A](ch: chan[A]): A =
  var a: A
  var ok = true
  while ok:
    (a, ok) = <-- ch
    if ok:
      yield a

proc printNumbers(numbers: chan[int], done: chan[bool]) {.goroutine.} =
  for n in numbers:
    echo n
  done <- true

proc numberGen(start, count: int, ch: chan[int]) {.goroutine.} =
  for i in 0 .. < count:
    ch <- start + i
  ch.close()

proc main() {.gomain.} =
  let
    numberChan = makeChan(int)
    done = makeChan(bool)
  go numberGen(1, 10, numberChan)
  go printNumbers(numberChan, done)
  discard <- done

when isMainModule:
  golibMain()
```

I defined `items` locally but it seemed a general-purpose thing, which is why I submitted it

**Comment by stefantalpalaru** [comment]
Merged, along with a test that uses iteration over channels and some short documentation. Thank you for the contribution.

**Comment by andreaferretti** [comment]
Thank you! I am sorry I had a few busy days and did not just write the tests myself

**Pull request merged**
